#!/usr/bin/env python3
import re
txt = open('/home/sanonichan/projetos/plataformgame/src/assets/Sprites/PlayerParts.h').read()
names = re.findall(r'inline const char\* const (\w+)\[\] = \{', txt)
assert len(names) == 134, len(names)
L = []
L.append('/**')
L.append(' * @file tests/test_player_palette.cpp')
L.append(' * @brief Trava invariantes I1-I5 do manual de PlayerParts.h.')
L.append(' * @details I1 (40 rows) via static_assert por array (gerado);')
L.append(' * I2/I3/I4 em runtime sobre todos os 134 arrays; I5 sobre todos')
L.append(' * os Parts de posePartsFor/posePartsForAir. Arte nova entra aqui')
L.append(' * regenerando a lista (mesmo script que gerou).')
L.append(' */')
L.append('#include <cassert>')
L.append('#include <cstdio>')
L.append('#include <cstring>')
L.append('#include <set>')
L.append('#include <string>')
L.append('#include "assets/SpriteComposer.h"')
L.append('#include "assets/Sprites/PlayerParts.h"')
L.append('#include "assets/Sprites/PlayerPalette.h"')
L.append('#include "assets/Sprites/PlayerSprites.h"')
L.append('')
L.append('namespace {')
L.append('struct Span { int lo, hi; };')
L.append('Span spanFor(const char* name) {')
L.append('    std::string n(name);')
L.append('    if (n == "kPlayerJumpArms" || n == "kPlayerHurtArms" ||')
L.append('        n == "kPlayerPunchUpArms")')
L.append('        return {0, 13}; // exceção Arms-em-y=0 (manual)')
L.append('    if (n.size() >= 4 && n.compare(n.size() - 4, 4, "Head") == 0)')
L.append('        return {0, 11};')
L.append('    if (n.size() >= 5 && n.compare(n.size() - 5, 5, "Torso") == 0)')
L.append('        return {12, 27};')
L.append('    if (n.size() >= 4 && n.compare(n.size() - 4, 4, "Legs") == 0)')
L.append('        return {28, 33};')
L.append('    if (n.size() >= 4 && n.compare(n.size() - 4, 4, "Feet") == 0)')
L.append('        return {34, 39};')
L.append('    if (n.size() >= 4 && n.compare(n.size() - 4, 4, "Arms") == 0)')
L.append('        return {12, 27};')
L.append('    return {-1, -1}; // sem kind: falha abaixo')
L.append('}')
L.append('} // namespace')
L.append('')
L.append('// I1: 40 rows por array (tempo de compilação).')
for n in names:
    L.append('static_assert(sizeof(sprites::' + n + ') / sizeof(sprites::' + n + '[0]) == 40, "' + n + '");')
L.append('')
L.append('int main() {')
L.append('    using namespace sprites;')
L.append('    static const char* const* kArrays[] = {')
for n in names:
    L.append('        ' + n + ',')
L.append('    };')
L.append('    static const char* kNames[] = {')
for n in names:
    L.append('        "' + n + '",')
L.append('    };')
L.append('    constexpr int N = static_cast<int>(sizeof(kArrays) / sizeof(kArrays[0]));')
L.append('    assert(N == 134);')
L.append('    std::set<char> pal;')
L.append('    for (std::size_t i = 0; i < kPlayerPaletteCount; ++i)')
L.append('        pal.insert(kPlayerPalette[i].ch);')
L.append('    for (int i = 0; i < N; ++i) {')
L.append('        Span sp = spanFor(kNames[i]);')
L.append('        assert(sp.lo >= 0); // I4: kind conhecido')
L.append('        int lo = 40, hi = -1;')
L.append('        for (int y = 0; y < 40; ++y) {')
L.append('            assert(std::strlen(kArrays[i][y]) == 40); // I2')
L.append("            assert(kArrays[i][y][0] != 0); // nunca string vazia")
L.append('            for (int x = 0; x < 40; ++x) {')
L.append('                const char c = kArrays[i][y][x];')
L.append("                if (c == '.') continue;")
L.append('                assert(pal.count(c) && "I3: char sem entrada na paleta");')
L.append('                if (y < lo) lo = y;')
L.append('                if (y > hi) hi = y;')
L.append('            }')
L.append('        }')
L.append('        if (hi >= 0) { // I4: conteúdo dentro do span (vazio passa)')
L.append('            assert(lo >= sp.lo && hi <= sp.hi);')
L.append('        }')
L.append('    }')
L.append('    for (int pi = 0; pi < kPlayerPoseCount; ++pi) { // I5')
L.append('        auto pose = static_cast<PlayerPose>(pi);')
L.append('        for (int di = 0; di < kArtDirCount; ++di) {')
L.append('            const assets::Part* pp =')
L.append('                posePartsFor(pose, artDirForIndex(di));')
L.append('            for (int k = 0; k < 5; ++k) {')
L.append('                assert(pp[k].w == 40 && pp[k].h == 40);')
L.append('                assert(pp[k].offX == 0 && pp[k].offY == 0);')
L.append('            }')
L.append('        }')
L.append('        if (const assets::Part* ap = posePartsForAir(pose))')
L.append('            for (int k = 0; k < 5; ++k) {')
L.append('                assert(ap[k].w == 40 && ap[k].h == 40);')
L.append('                assert(ap[k].offX == 0 && ap[k].offY == 0);')
L.append('            }')
L.append('    }')
L.append('    std::printf("player palette test OK\\n");')
L.append('    return 0;')
L.append('}')
open('/home/sanonichan/projetos/plataformgame/tests/test_player_palette.cpp', 'w').write('\n'.join(L) + '\n')
print('written')
