/**
 * @file src/assets/Sprites/PlayerSprites.h
 * @author Matheus de Camargo Marques <matheuscamarques@gmail.com>
 * @brief Define sprites ASCII e paleta do jogador 12x40.
 * @details Contém largura, altura, paleta com partes do corpo e frames idle, walk, jump, throw, punch, hurt e death, usados por SpriteSet e testes de largura.
 */

#pragma once

#include "core/sprite_from_ascii.h"

namespace sprites {

// Player 12x40 (stretch 2x vertical do 12x20; slime 14x12, dwarf 14x18).
// Top compartilhado via macros; teste trava widths (linha errada =
// sprite deslocada).

inline constexpr int kPlayerW = 12;
inline constexpr int kPlayerH = 40;

inline const core::PaletteEntry kPlayerPal[] = {
    {'.', {0, 0, 0, 0}, core::BodyPartId::None},
    {'K', {30, 20, 20}, core::BodyPartId::None},
    {'F', {230, 180, 140}, core::BodyPartId::Head},
    {'H', {230, 180, 140}, core::BodyPartId::ArmR},
    {'G', {230, 180, 140}, core::BodyPartId::ArmL},
    {'E', {20, 15, 15}, core::BodyPartId::Head},
    {'C', {60, 90, 160}, core::BodyPartId::Torso},
    {'B', {50, 35, 30}, core::BodyPartId::LegR},
    {'L', {50, 35, 30}, core::BodyPartId::LegL},
    {'W', {190, 190, 200}, core::BodyPartId::Weapon},
    {'T', {220, 60, 50}, core::BodyPartId::Weapon},
    {'t', {90, 30, 25}, core::BodyPartId::Weapon},
};
inline constexpr std::size_t kPlayerPalCount = 12;

inline const char *const kPlayerIdle[] = {
    "....KKKK....",
    "....KKKK....",
    "..KKKKKKKK..",
    "..KKKKKKKK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "............",
    "............",
};

inline const char *const kPlayerWalkA[] = {
    "....KKKK....",
    "....KKKK....",
    "..KKKKKKKK..",
    "..KKKKKKKK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "............",
    "............",
};

inline const char *const kPlayerWalkB[] = {
    "....KKKK....",
    "....KKKK....",
    "..KKKKKKKK..",
    "..KKKKKKKK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCCH.",
    "..CCCCCCCCH.",
    "..CCCCCCCCH.",
    "..CCCCCCCCH.",
    "..CCCCCCCCH.",
    "..CCCCCCCCH.",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "..CC....CC..",
    "..CC....CC..",
    "..CC....CC..",
    "..CC....CC..",
    ".LL......BB.",
    ".LL......BB.",
    ".LL......BB.",
    ".LL......BB.",
    ".LL......BB.",
    ".LL......BB.",
    "............",
    "............",
};
inline const char *const kPlayerJump[] = {
    ".G........H.",
    ".G........H.",
    ".G.KKKKKK.H.",
    ".G.KKKKKK.H.",
    ".GKKKKKKKKH.",
    ".GKKKKKKKKH.",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "..LL....BB..",
    "..LL....BB..",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
};

inline const char *const kPlayerThrow[] = {
    "....KKKK..TT",
    "....KKKK..TT",
    "..KKKKKKKKtT",
    "..KKKKKKKKtT",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    ".GCCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
};

inline const char *const kPlayerPunch[] = {
    "....KKKK....",
    "....KKKK....",
    "..KKKKKKKK..",
    "..KKKKKKKK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCCH.",
    "..CCCCCCCCH.",
    "..CCCCCCCCHH",
    "..CCCCCCCCHH",
    "..CCCCCCCCH.",
    "..CCCCCCCCH.",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "............",
    "............",
};

inline const char *const kPlayerPunchUp[] = {
    ".GG......HH.",
    ".GG......HH.",
    ".GG......HH.",
    ".GG......HH.",
    ".G..KKKK..H.",
    ".G..KKKK..H.",
    ".GKKKKKKKKH.",
    ".GKKKKKKKKH.",
    ".GKFFFFFFKH.",
    ".GKFFFFFFKH.",
    ".GKFEFFEFKH.",
    ".GKFEFFEFKH.",
    ".GKFFFFFFKH.",
    ".GKFFFFFFKH.",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "............",
    "............",
};

inline const char *const kPlayerPunchDown[] = {
    "....KKKK....",
    "....KKKK....",
    "..KKKKKKKK..",
    "..KKKKKKKK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    "..GCCCCCCH..",
    "..GCCCCCCH..",
    "..GCCCCCCH..",
    "..GCCCCCCH..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...CC..CC...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "...LL..BB...",
    "............",
    "............",
};

inline const char *const kPlayerHurt[] = {
    ".G........H.",
    ".G........H.",
    ".G.KKKKKK.H.",
    ".G.KKKKKK.H.",
    ".GKKKKKKKKH.",
    ".GKKKKKKKKH.",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "...FFFFFF...",
    "...FFFFFF...",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CC..CC...",
    "...CC..CC...",
    "..CC....CC..",
    "..CC....CC..",
    "..LL....BB..",
    "..LL....BB..",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
};

inline const char *const kPlayerDeath[] = {
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "....KKKK....",
    "....KKKK....",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..KFEFFEFK..",
    "..KFEFFEFK..",
    "..KFFFFFFK..",
    "..KFFFFFFK..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    ".GCCCCCCCCH.",
    ".GCCCCCCCCH.",
    "..CCCCCCCC..",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "...CCCCCC...",
    "..CC....CC..",
    "..CC....CC..",
    "..CC....CC..",
    "..CC....CC..",
    ".LL......BB.",
    ".LL......BB.",
    "LL........BB",
    "LL........BB",
    "............",
    "............",
};

} // namespace sprites
